#!/usr/bin/python

import os
import sys

fd_null = os.open("/dev/null", os.O_RDWR)
os.dup2(fd_null, 0)
os.dup2(fd_null, 1)
os.dup2(fd_null, 2)

if os.fork() == 0:
    os.execlp(*([sys.argv[1]] + sys.argv[1:]))
else:
    sys.exit()
