#!/bin/sh

case $1 in 
    start) 
        echo "Starting..."
        ssh eom@exorg.ru "cd eo-svr; ./start.sh"
        ;;

    stop) 
        echo "Stopping..."
        ssh eom@exorg.ru "killall java"
        ;;
    sync)
	echo "Synchronizing..."
	./archive-server.sh
	scp svr.tar.bz2 eom@exorg.ru:eo-svr/
	ssh eom@exorg.ru "cd eo-svr; tar -xjf svr.tar.bz2"
	;;
esac
