#!/bin/sh

case $1 in 
    start) 
        echo "Starting..."
        ssh eom@exorg.ru "cd eo-svr; ./start.sh"
        ;;

    stop) 
        echo "Stopping..."
        ssh eom@exorg.ru "killall java; killall searchd"
        ;;
esac
