#!/bin/sh

case $1 in 
    start) 
        echo "Starting..."
        ssh eom@exorg.ru "cd /home/eom/eo-svr; source init_env.sh; frontend/http_server/script/run -D"
        ;;

    stop) 
        echo "Stopping..."
        ssh eom@exorg.ru "killall java; killall searchd"
        ;;
esac
